/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAFunctionParameters extends PAFunctionParameters
{
    private final LinkedList<PAParameters> _aParameters_ = new LinkedList<PAParameters>();

    public AAFunctionParameters()
    {
        // Constructor
    }

    public AAFunctionParameters(
        @SuppressWarnings("hiding") List<PAParameters> _aParameters_)
    {
        // Constructor
        setAParameters(_aParameters_);

    }

    @Override
    public Object clone()
    {
        return new AAFunctionParameters(
            cloneList(this._aParameters_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAFunctionParameters(this);
    }

    public LinkedList<PAParameters> getAParameters()
    {
        return this._aParameters_;
    }

    public void setAParameters(List<PAParameters> list)
    {
        this._aParameters_.clear();
        this._aParameters_.addAll(list);
        for(PAParameters e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aParameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aParameters_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAParameters> i = this._aParameters_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAParameters) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
