/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAssignFunctionParameter extends PParameter
{
    private PAssignFunction _assignFunction_;

    public AAssignFunctionParameter()
    {
        // Constructor
    }

    public AAssignFunctionParameter(
        @SuppressWarnings("hiding") PAssignFunction _assignFunction_)
    {
        // Constructor
        setAssignFunction(_assignFunction_);

    }

    @Override
    public Object clone()
    {
        return new AAssignFunctionParameter(
            cloneNode(this._assignFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignFunctionParameter(this);
    }

    public PAssignFunction getAssignFunction()
    {
        return this._assignFunction_;
    }

    public void setAssignFunction(PAssignFunction node)
    {
        if(this._assignFunction_ != null)
        {
            this._assignFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignFunction_ == child)
        {
            this._assignFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignFunction_ == oldChild)
        {
            setAssignFunction((PAssignFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
