/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ABlockExpressionTerm extends PTerm
{
    private PBlockExpression _blockExpression_;

    public ABlockExpressionTerm()
    {
        // Constructor
    }

    public ABlockExpressionTerm(
        @SuppressWarnings("hiding") PBlockExpression _blockExpression_)
    {
        // Constructor
        setBlockExpression(_blockExpression_);

    }

    @Override
    public Object clone()
    {
        return new ABlockExpressionTerm(
            cloneNode(this._blockExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockExpressionTerm(this);
    }

    public PBlockExpression getBlockExpression()
    {
        return this._blockExpression_;
    }

    public void setBlockExpression(PBlockExpression node)
    {
        if(this._blockExpression_ != null)
        {
            this._blockExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockExpression_ == child)
        {
            this._blockExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockExpression_ == oldChild)
        {
            setBlockExpression((PBlockExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
