/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACallFunctionCallFunction extends PCallFunction
{
    private TIdentifier _identifier_;
    private TLeftParentheses _leftParentheses_;
    private PListExpressions _listExpressions_;
    private TRightParentheses _rightParentheses_;

    public ACallFunctionCallFunction()
    {
        // Constructor
    }

    public ACallFunctionCallFunction(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TLeftParentheses _leftParentheses_,
        @SuppressWarnings("hiding") PListExpressions _listExpressions_,
        @SuppressWarnings("hiding") TRightParentheses _rightParentheses_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setLeftParentheses(_leftParentheses_);

        setListExpressions(_listExpressions_);

        setRightParentheses(_rightParentheses_);

    }

    @Override
    public Object clone()
    {
        return new ACallFunctionCallFunction(
            cloneNode(this._identifier_),
            cloneNode(this._leftParentheses_),
            cloneNode(this._listExpressions_),
            cloneNode(this._rightParentheses_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallFunctionCallFunction(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TLeftParentheses getLeftParentheses()
    {
        return this._leftParentheses_;
    }

    public void setLeftParentheses(TLeftParentheses node)
    {
        if(this._leftParentheses_ != null)
        {
            this._leftParentheses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftParentheses_ = node;
    }

    public PListExpressions getListExpressions()
    {
        return this._listExpressions_;
    }

    public void setListExpressions(PListExpressions node)
    {
        if(this._listExpressions_ != null)
        {
            this._listExpressions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listExpressions_ = node;
    }

    public TRightParentheses getRightParentheses()
    {
        return this._rightParentheses_;
    }

    public void setRightParentheses(TRightParentheses node)
    {
        if(this._rightParentheses_ != null)
        {
            this._rightParentheses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightParentheses_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._leftParentheses_)
            + toString(this._listExpressions_)
            + toString(this._rightParentheses_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._leftParentheses_ == child)
        {
            this._leftParentheses_ = null;
            return;
        }

        if(this._listExpressions_ == child)
        {
            this._listExpressions_ = null;
            return;
        }

        if(this._rightParentheses_ == child)
        {
            this._rightParentheses_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._leftParentheses_ == oldChild)
        {
            setLeftParentheses((TLeftParentheses) newChild);
            return;
        }

        if(this._listExpressions_ == oldChild)
        {
            setListExpressions((PListExpressions) newChild);
            return;
        }

        if(this._rightParentheses_ == oldChild)
        {
            setRightParentheses((TRightParentheses) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
