/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfThenElseStatement extends PIfThenElseStatement
{
    private PIfStatement _ifStatement_;
    private TThen _then_;
    private PTerm _term_;
    private PElseStatement _elseStatement_;

    public AIfThenElseStatement()
    {
        // Constructor
    }

    public AIfThenElseStatement(
        @SuppressWarnings("hiding") PIfStatement _ifStatement_,
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") PElseStatement _elseStatement_)
    {
        // Constructor
        setIfStatement(_ifStatement_);

        setThen(_then_);

        setTerm(_term_);

        setElseStatement(_elseStatement_);

    }

    @Override
    public Object clone()
    {
        return new AIfThenElseStatement(
            cloneNode(this._ifStatement_),
            cloneNode(this._then_),
            cloneNode(this._term_),
            cloneNode(this._elseStatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfThenElseStatement(this);
    }

    public PIfStatement getIfStatement()
    {
        return this._ifStatement_;
    }

    public void setIfStatement(PIfStatement node)
    {
        if(this._ifStatement_ != null)
        {
            this._ifStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifStatement_ = node;
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public PElseStatement getElseStatement()
    {
        return this._elseStatement_;
    }

    public void setElseStatement(PElseStatement node)
    {
        if(this._elseStatement_ != null)
        {
            this._elseStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifStatement_)
            + toString(this._then_)
            + toString(this._term_)
            + toString(this._elseStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifStatement_ == child)
        {
            this._ifStatement_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._elseStatement_ == child)
        {
            this._elseStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifStatement_ == oldChild)
        {
            setIfStatement((PIfStatement) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._elseStatement_ == oldChild)
        {
            setElseStatement((PElseStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
