/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ALambdaListExpressions extends PLambdaListExpressions
{
    private PExpression _expression_;
    private final LinkedList<PLambdaListExpressionsAuxiliar> _lambdaListExpressionsAuxiliar_ = new LinkedList<PLambdaListExpressionsAuxiliar>();

    public ALambdaListExpressions()
    {
        // Constructor
    }

    public ALambdaListExpressions(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<PLambdaListExpressionsAuxiliar> _lambdaListExpressionsAuxiliar_)
    {
        // Constructor
        setExpression(_expression_);

        setLambdaListExpressionsAuxiliar(_lambdaListExpressionsAuxiliar_);

    }

    @Override
    public Object clone()
    {
        return new ALambdaListExpressions(
            cloneNode(this._expression_),
            cloneList(this._lambdaListExpressionsAuxiliar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALambdaListExpressions(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PLambdaListExpressionsAuxiliar> getLambdaListExpressionsAuxiliar()
    {
        return this._lambdaListExpressionsAuxiliar_;
    }

    public void setLambdaListExpressionsAuxiliar(List<PLambdaListExpressionsAuxiliar> list)
    {
        this._lambdaListExpressionsAuxiliar_.clear();
        this._lambdaListExpressionsAuxiliar_.addAll(list);
        for(PLambdaListExpressionsAuxiliar e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._lambdaListExpressionsAuxiliar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._lambdaListExpressionsAuxiliar_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PLambdaListExpressionsAuxiliar> i = this._lambdaListExpressionsAuxiliar_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLambdaListExpressionsAuxiliar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
