/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AListIdentifiers extends PListIdentifiers
{
    private TIdentifier _identifier_;
    private final LinkedList<PListIdentifiersAux> _listIdentifiersAux_ = new LinkedList<PListIdentifiersAux>();

    public AListIdentifiers()
    {
        // Constructor
    }

    public AListIdentifiers(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<PListIdentifiersAux> _listIdentifiersAux_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setListIdentifiersAux(_listIdentifiersAux_);

    }

    @Override
    public Object clone()
    {
        return new AListIdentifiers(
            cloneNode(this._identifier_),
            cloneList(this._listIdentifiersAux_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListIdentifiers(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PListIdentifiersAux> getListIdentifiersAux()
    {
        return this._listIdentifiersAux_;
    }

    public void setListIdentifiersAux(List<PListIdentifiersAux> list)
    {
        this._listIdentifiersAux_.clear();
        this._listIdentifiersAux_.addAll(list);
        for(PListIdentifiersAux e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._listIdentifiersAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._listIdentifiersAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PListIdentifiersAux> i = this._listIdentifiersAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListIdentifiersAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
