/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AListExpressions extends PListExpressions
{
    private PExpression _expression_;
    private final LinkedList<PListExpressionsSequence> _listExpressionsSequence_ = new LinkedList<PListExpressionsSequence>();

    public AListExpressions()
    {
        // Constructor
    }

    public AListExpressions(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<PListExpressionsSequence> _listExpressionsSequence_)
    {
        // Constructor
        setExpression(_expression_);

        setListExpressionsSequence(_listExpressionsSequence_);

    }

    @Override
    public Object clone()
    {
        return new AListExpressions(
            cloneNode(this._expression_),
            cloneList(this._listExpressionsSequence_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListExpressions(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PListExpressionsSequence> getListExpressionsSequence()
    {
        return this._listExpressionsSequence_;
    }

    public void setListExpressionsSequence(List<PListExpressionsSequence> list)
    {
        this._listExpressionsSequence_.clear();
        this._listExpressionsSequence_.addAll(list);
        for(PListExpressionsSequence e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._listExpressionsSequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._listExpressionsSequence_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PListExpressionsSequence> i = this._listExpressionsSequence_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListExpressionsSequence) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
