/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AListExpressionsListExpressions extends PListExpressions
{
    private PExpression _expression_;
    private final LinkedList<PListExpressionsAux> _listExpressionsAux_ = new LinkedList<PListExpressionsAux>();

    public AListExpressionsListExpressions()
    {
        // Constructor
    }

    public AListExpressionsListExpressions(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<PListExpressionsAux> _listExpressionsAux_)
    {
        // Constructor
        setExpression(_expression_);

        setListExpressionsAux(_listExpressionsAux_);

    }

    @Override
    public Object clone()
    {
        return new AListExpressionsListExpressions(
            cloneNode(this._expression_),
            cloneList(this._listExpressionsAux_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListExpressionsListExpressions(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PListExpressionsAux> getListExpressionsAux()
    {
        return this._listExpressionsAux_;
    }

    public void setListExpressionsAux(List<PListExpressionsAux> list)
    {
        this._listExpressionsAux_.clear();
        this._listExpressionsAux_.addAll(list);
        for(PListExpressionsAux e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._listExpressionsAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._listExpressionsAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PListExpressionsAux> i = this._listExpressionsAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListExpressionsAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
