/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANegationExpression extends PExpression
{
    private TExclamation _exclamation_;
    private POperation _operation_;

    public ANegationExpression()
    {
        // Constructor
    }

    public ANegationExpression(
        @SuppressWarnings("hiding") TExclamation _exclamation_,
        @SuppressWarnings("hiding") POperation _operation_)
    {
        // Constructor
        setExclamation(_exclamation_);

        setOperation(_operation_);

    }

    @Override
    public Object clone()
    {
        return new ANegationExpression(
            cloneNode(this._exclamation_),
            cloneNode(this._operation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegationExpression(this);
    }

    public TExclamation getExclamation()
    {
        return this._exclamation_;
    }

    public void setExclamation(TExclamation node)
    {
        if(this._exclamation_ != null)
        {
            this._exclamation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclamation_ = node;
    }

    public POperation getOperation()
    {
        return this._operation_;
    }

    public void setOperation(POperation node)
    {
        if(this._operation_ != null)
        {
            this._operation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exclamation_)
            + toString(this._operation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exclamation_ == child)
        {
            this._exclamation_ = null;
            return;
        }

        if(this._operation_ == child)
        {
            this._operation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exclamation_ == oldChild)
        {
            setExclamation((TExclamation) newChild);
            return;
        }

        if(this._operation_ == oldChild)
        {
            setOperation((POperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
