/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANegativeNumberFactor extends PFactor
{
    private PNegativeNumber _negativeNumber_;

    public ANegativeNumberFactor()
    {
        // Constructor
    }

    public ANegativeNumberFactor(
        @SuppressWarnings("hiding") PNegativeNumber _negativeNumber_)
    {
        // Constructor
        setNegativeNumber(_negativeNumber_);

    }

    @Override
    public Object clone()
    {
        return new ANegativeNumberFactor(
            cloneNode(this._negativeNumber_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativeNumberFactor(this);
    }

    public PNegativeNumber getNegativeNumber()
    {
        return this._negativeNumber_;
    }

    public void setNegativeNumber(PNegativeNumber node)
    {
        if(this._negativeNumber_ != null)
        {
            this._negativeNumber_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negativeNumber_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negativeNumber_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negativeNumber_ == child)
        {
            this._negativeNumber_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negativeNumber_ == oldChild)
        {
            setNegativeNumber((PNegativeNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
