/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANegBoolExpression extends PExpression
{
    private TExclamation _exclamation_;
    private POp _op_;

    public ANegBoolExpression()
    {
        // Constructor
    }

    public ANegBoolExpression(
        @SuppressWarnings("hiding") TExclamation _exclamation_,
        @SuppressWarnings("hiding") POp _op_)
    {
        // Constructor
        setExclamation(_exclamation_);

        setOp(_op_);

    }

    @Override
    public Object clone()
    {
        return new ANegBoolExpression(
            cloneNode(this._exclamation_),
            cloneNode(this._op_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegBoolExpression(this);
    }

    public TExclamation getExclamation()
    {
        return this._exclamation_;
    }

    public void setExclamation(TExclamation node)
    {
        if(this._exclamation_ != null)
        {
            this._exclamation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclamation_ = node;
    }

    public POp getOp()
    {
        return this._op_;
    }

    public void setOp(POp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exclamation_)
            + toString(this._op_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exclamation_ == child)
        {
            this._exclamation_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exclamation_ == oldChild)
        {
            setExclamation((TExclamation) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((POp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
