/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AParametersAssignAux extends PParametersAssignAux
{
    private TComma _comma_;
    private PParametersAssign _parametersAssign_;

    public AParametersAssignAux()
    {
        // Constructor
    }

    public AParametersAssignAux(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PParametersAssign _parametersAssign_)
    {
        // Constructor
        setComma(_comma_);

        setParametersAssign(_parametersAssign_);

    }

    @Override
    public Object clone()
    {
        return new AParametersAssignAux(
            cloneNode(this._comma_),
            cloneNode(this._parametersAssign_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametersAssignAux(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PParametersAssign getParametersAssign()
    {
        return this._parametersAssign_;
    }

    public void setParametersAssign(PParametersAssign node)
    {
        if(this._parametersAssign_ != null)
        {
            this._parametersAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametersAssign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._parametersAssign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._parametersAssign_ == child)
        {
            this._parametersAssign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._parametersAssign_ == oldChild)
        {
            setParametersAssign((PParametersAssign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
